import type { IndustryData } from '@/components/industry-page';

export const industriesData: Record<string, Record<string, IndustryData>> = {
  restaurants: {
    de: {
      slug: 'restaurants',
      emoji: '🍽️',
      badge: 'Restaurants & Gastronomie',
      heroTitle: 'Mehr Reservierungen.',
      heroGradient: 'Weniger manuelle Arbeit.',
      heroSub: 'Restaurants verlieren täglich Umsatz durch verpasste Anfragen und manuelle Prozesse. Ovivo automatisiert alles — von der Reservierung bis zum Follow-up.',
      painPoints: [
        { icon: '📞', title: 'Verpasste Anrufe', desc: 'Kunden rufen an, während Sie beschäftigt sind. Jeder verpasste Anruf ist ein verlorener Tisch.' },
        { icon: '💬', title: 'WhatsApp-Chaos', desc: 'Anfragen kommen von überall. Kein System, keine Übersicht — alles manuell.' },
        { icon: '🚫', title: 'No-Shows', desc: 'Gäste erscheinen nicht. Keine automatischen Erinnerungen = leere Tische und verlorener Umsatz.' },
        { icon: '⭐', title: 'Zu wenig Bewertungen', desc: 'Zufriedene Gäste vergessen zu bewerten. Unzufriedene schreiben sofort.' },
      ],
      solutions: [
        { title: 'Automatische Reservierungen 24/7', desc: 'KI nimmt Reservierungen entgegen — per WhatsApp, Website oder Telefon — auch nachts und am Wochenende.', result: '+40% mehr Buchungen' },
        { title: 'No-Show Reduktion', desc: 'Automatische Erinnerungen per WhatsApp 24h und 2h vor dem Termin. No-Show-Rate sinkt um bis zu 60%.', result: '-60% No-Shows' },
        { title: 'Bewertungs-Automation', desc: 'Nach jedem Besuch geht automatisch eine freundliche Nachricht raus — mit Link zu Google oder TripAdvisor.', result: '+3x mehr Bewertungen' },
      ],
      stats: [
        { value: '+40%', label: 'Mehr Reservierungen' },
        { value: '-60%', label: 'Weniger No-Shows' },
        { value: '3h', label: 'Tägliche Zeitersparnis' },
        { value: '24/7', label: 'Immer erreichbar' },
      ],
      caseStudy: {
        name: 'Restaurant Bella Vista, München',
        result: '+35% Umsatz in 3 Monaten',
        quote: 'Seit Ovivo kümmert sich der Chatbot um alle Reservierungen. Wir sparen täglich 2 Stunden und haben 35% mehr Umsatz gemacht — ohne einen einzigen neuen Mitarbeiter.',
      },
      automations: [
        'Tischreservierungen per WhatsApp & Website',
        'Bestätigungen & Erinnerungen automatisch',
        'Speisekarte & Öffnungszeiten beantworten',
        'Bewertungsanfragen nach dem Besuch',
        'Follow-up für Geburtstage & Jubiläen',
        'Wartelisten-Management',
        'Gutschein & Aktions-Broadcasts',
        'CRM mit Stammkunden-Daten',
      ],
      faq: [
        { q: 'Funktioniert das auch für kleine Restaurants?', a: 'Ja, gerade für kleinere Betriebe ist Automation besonders wertvoll — weil das Team kleiner ist und jede gesparte Stunde zählt.' },
        { q: 'Wie lange dauert die Einrichtung?', a: 'Das System ist in 5–10 Werktagen live. Wir kümmern uns um alles, Sie müssen nichts Technisches tun.' },
        { q: 'Was passiert bei Sonderwünschen oder Allergien?', a: 'Der KI-Assistent kann spezifische Fragen beantworten und komplexere Anfragen automatisch an Sie weiterleiten.' },
      ],
    },
    en: {
      slug: 'restaurants',
      emoji: '🍽️',
      badge: 'Restaurants & Hospitality',
      heroTitle: 'More reservations.',
      heroGradient: 'Less manual work.',
      heroSub: 'Restaurants lose revenue daily from missed inquiries and manual processes. Ovivo automates everything — from reservation to follow-up.',
      painPoints: [
        { icon: '📞', title: 'Missed calls', desc: 'Customers call while you\'re busy. Every missed call is a lost table.' },
        { icon: '💬', title: 'WhatsApp chaos', desc: 'Inquiries come from everywhere. No system, no overview — everything manual.' },
        { icon: '🚫', title: 'No-shows', desc: 'Guests don\'t show up. No automatic reminders = empty tables and lost revenue.' },
        { icon: '⭐', title: 'Too few reviews', desc: 'Satisfied guests forget to review. Unsatisfied ones write immediately.' },
      ],
      solutions: [
        { title: 'Automatic reservations 24/7', desc: 'AI takes reservations via WhatsApp, website or phone — even at night and on weekends.', result: '+40% more bookings' },
        { title: 'No-show reduction', desc: 'Automatic WhatsApp reminders 24h and 2h before the reservation. No-show rate drops by up to 60%.', result: '-60% no-shows' },
        { title: 'Review automation', desc: 'After every visit, a friendly message goes out automatically — with a link to Google or TripAdvisor.', result: '+3x more reviews' },
      ],
      stats: [
        { value: '+40%', label: 'More reservations' },
        { value: '-60%', label: 'Fewer no-shows' },
        { value: '3h', label: 'Daily time saved' },
        { value: '24/7', label: 'Always available' },
      ],
      caseStudy: {
        name: 'Restaurant Bella Vista, Munich',
        result: '+35% revenue in 3 months',
        quote: 'Since Ovivo, the chatbot handles all reservations. We save 2 hours daily and generated 35% more revenue — without a single new employee.',
      },
      automations: [
        'Table reservations via WhatsApp & website',
        'Automatic confirmations & reminders',
        'Menu & opening hours answered automatically',
        'Review requests after each visit',
        'Birthday & anniversary follow-ups',
        'Waitlist management',
        'Voucher & promotion broadcasts',
        'CRM with regular customer data',
      ],
      faq: [
        { q: 'Does this work for small restaurants too?', a: 'Yes, automation is especially valuable for smaller operations — because the team is smaller and every saved hour counts.' },
        { q: 'How long does setup take?', a: 'The system is live in 5–10 business days. We handle everything, you don\'t need to do anything technical.' },
        { q: 'What about special requests or allergies?', a: 'The AI assistant can answer specific questions and automatically forward complex inquiries to you.' },
      ],
    },
    ar: {
      slug: 'restaurants',
      emoji: '🍽️',
      badge: 'المطاعم والضيافة',
      heroTitle: 'المزيد من الحجوزات.',
      heroGradient: 'أقل عمل يدوي.',
      heroSub: 'تخسر المطاعم إيرادات يومياً من الاستفسارات الفائتة والعمليات اليدوية. أوفيفو يؤتمت كل شيء — من الحجز إلى المتابعة.',
      painPoints: [
        { icon: '📞', title: 'مكالمات فائتة', desc: 'يتصل العملاء وأنت مشغول. كل مكالمة فائتة تعني طاولة ضائعة وإيراد مفقود.' },
        { icon: '💬', title: 'فوضى واتساب', desc: 'الاستفسارات تأتي من كل مكان. لا نظام، لا ترتيب — كل شيء يدوي.' },
        { icon: '🚫', title: 'الحجوزات الملغاة', desc: 'الضيوف لا يحضرون. بدون تذكيرات تلقائية = طاولات فارغة وخسائر يومية.' },
        { icon: '⭐', title: 'قلة التقييمات', desc: 'الضيوف الراضون ينسون التقييم. الغاضبون يكتبون فوراً.' },
      ],
      solutions: [
        { title: 'حجوزات تلقائية 24/7', desc: 'الذكاء الاصطناعي يستقبل الحجوزات عبر واتساب والموقع والهاتف — حتى ليلاً وفي العطل.', result: '+40% حجوزات أكثر' },
        { title: 'تقليل الإلغاءات', desc: 'تذكيرات واتساب تلقائية قبل 24 ساعة و2 ساعة من الموعد. نسبة الغياب تنخفض حتى 60%.', result: '-60% إلغاء' },
        { title: 'أتمتة التقييمات', desc: 'بعد كل زيارة ترسل رسالة ودية تلقائياً مع رابط Google أو TripAdvisor.', result: '+3x تقييمات أكثر' },
      ],
      stats: [
        { value: '+40%', label: 'حجوزات أكثر' },
        { value: '-60%', label: 'إلغاءات أقل' },
        { value: '3h', label: 'توفير يومي' },
        { value: '24/7', label: 'متاح دائماً' },
      ],
      caseStudy: {
        name: 'مطعم بيلا فيستا، ميونخ',
        result: '+35% إيرادات في 3 أشهر',
        quote: 'منذ تركيب أوفيفو، يتولى الشات جميع الحجوزات. نوفر ساعتين يومياً وحققنا 35% إيرادات أكثر — بدون أي موظف جديد.',
      },
      automations: [
        'حجز الطاولات عبر واتساب والموقع',
        'تأكيدات وتذكيرات تلقائية',
        'الإجابة على أسئلة القائمة وأوقات العمل',
        'طلب التقييمات بعد الزيارة',
        'متابعة أعياد الميلاد والمناسبات',
        'إدارة قوائم الانتظار',
        'بث العروض والكوبونات',
        'CRM مع بيانات العملاء الدائمين',
      ],
      faq: [
        { q: 'هل يناسب المطاعم الصغيرة؟', a: 'نعم، الأتمتة مفيدة بشكل خاص للمطاعم الصغيرة — لأن الفريق أصغر وكل ساعة موفرة تحسب.' },
        { q: 'كم يستغرق الإعداد؟', a: 'النظام يعمل خلال 5–10 أيام عمل. نتولى كل شيء، أنت لا تحتاج أي خبرة تقنية.' },
        { q: 'ماذا عن الطلبات الخاصة والحساسية الغذائية؟', a: 'المساعد الذكي يجيب على أسئلة محددة ويحول الاستفسارات المعقدة إليك تلقائياً.' },
      ],
    },
  },
  beauty: {
    de: {
      slug: 'beauty',
      emoji: '💇',
      badge: 'Friseure & Beauty',
      heroTitle: 'Vollgebuchter Kalender.',
      heroGradient: 'Keine No-Shows mehr.',
      heroSub: 'Friseure und Beauty-Salons verlieren täglich Umsatz durch No-Shows und manuelle Terminbuchungen. Ovivo automatisiert Ihren Terminkalender vollständig.',
      painPoints: [
        { icon: '🚫', title: 'No-Shows zerstören den Tag', desc: 'Jeder No-Show kostet Sie Einnahmen und blockiert Ihren Kalender für zahlende Kunden.' },
        { icon: '📱', title: 'Ständig am Telefon', desc: 'Termine buchen, bestätigen, umbuchen — das frisst Ihre wertvolle Zeit.' },
        { icon: '😴', title: 'Keine Buchungen nach Feierabend', desc: 'Kunden möchten nachts buchen, aber niemand ist erreichbar. Potenzial verschenkt.' },
        { icon: '🔄', title: 'Stammkunden kommen nicht zurück', desc: 'Ohne automatische Erinnerungen vergessen Kunden den nächsten Termin.' },
      ],
      solutions: [
        { title: 'Online-Buchung rund um die Uhr', desc: 'Kunden buchen direkt über WhatsApp oder Ihre Website — ohne Telefon, ohne Wartezeit.', result: '+35% mehr Buchungen' },
        { title: 'Automatische Erinnerungen', desc: 'Zwei Tage und zwei Stunden vorher erinnert das System den Kunden automatisch — No-Show-Rate sinkt drastisch.', result: '-70% No-Shows' },
        { title: 'Stammkunden zurückgewinnen', desc: 'Das System erkennt, wann ein Kunde lange nicht da war, und sendet automatisch eine persönliche Einladung.', result: '+25% mehr Wiederkäufer' },
      ],
      stats: [
        { value: '+35%', label: 'Mehr Buchungen' },
        { value: '-70%', label: 'Weniger No-Shows' },
        { value: '2h', label: 'Täglich gespart' },
        { value: '+25%', label: 'Mehr Stammkunden' },
      ],
      caseStudy: {
        name: 'Salon Elise, Berlin',
        result: '-45% No-Shows, +30% Umsatz',
        quote: 'Früher hatte ich täglich 2–3 No-Shows. Seit Ovivo fast null. Der Kalender ist immer voll und ich spare 2 Stunden täglich für Buchungen.',
      },
      automations: [
        'Online-Terminbuchung 24/7',
        'Automatische Bestätigungen per WhatsApp',
        'Erinnerungen 48h und 2h vorher',
        'Umbuchungen ohne Telefon',
        'Stammkunden-Reaktivierung',
        'Bewertungsanfragen nach dem Termin',
        'Produkt & Angebots-Broadcasts',
        'Kundenkartei automatisch gepflegt',
      ],
      faq: [
        { q: 'Funktioniert das mit meiner bestehenden Buchungssoftware?', a: 'Ja, wir integrieren Ovivo in die meisten gängigen Buchungssysteme. Falls nicht, bauen wir ein maßgeschneidertes System.' },
        { q: 'Was, wenn Kunden lieber anrufen?', a: 'Kein Problem — das System funktioniert parallel. Wer anruft, wird automatisch zu WhatsApp oder zur Online-Buchung geleitet.' },
        { q: 'Wie persönlich sind die automatischen Nachrichten?', a: 'Sehr persönlich. Das System kennt den Namen, Lieblingsservice und letzte Termine — und schreibt entsprechend.' },
      ],
    },
    en: {
      slug: 'beauty',
      emoji: '💇',
      badge: 'Hair & Beauty',
      heroTitle: 'Fully booked calendar.',
      heroGradient: 'No more no-shows.',
      heroSub: 'Hair salons and beauty studios lose revenue daily from no-shows and manual bookings. Ovivo fully automates your appointment calendar.',
      painPoints: [
        { icon: '🚫', title: 'No-shows ruin your day', desc: 'Every no-show costs you income and blocks your calendar for paying customers.' },
        { icon: '📱', title: 'Always on the phone', desc: 'Booking, confirming, rebooking appointments — it eats your valuable time.' },
        { icon: '😴', title: 'No bookings after hours', desc: 'Customers want to book at night, but no one is available. Lost potential.' },
        { icon: '🔄', title: 'Regular clients don\'t return', desc: 'Without automatic reminders, clients forget their next appointment.' },
      ],
      solutions: [
        { title: 'Online booking around the clock', desc: 'Clients book directly via WhatsApp or your website — no phone, no waiting.', result: '+35% more bookings' },
        { title: 'Automatic reminders', desc: 'Two days and two hours before, the system automatically reminds the client — no-show rate drops drastically.', result: '-70% no-shows' },
        { title: 'Win back regular clients', desc: 'The system recognizes when a client hasn\'t visited in a while and automatically sends a personal invitation.', result: '+25% more returning clients' },
      ],
      stats: [
        { value: '+35%', label: 'More bookings' },
        { value: '-70%', label: 'Fewer no-shows' },
        { value: '2h', label: 'Saved daily' },
        { value: '+25%', label: 'More regulars' },
      ],
      caseStudy: {
        name: 'Salon Elise, Berlin',
        result: '-45% no-shows, +30% revenue',
        quote: 'I used to have 2–3 no-shows daily. Since Ovivo, almost zero. The calendar is always full and I save 2 hours daily on bookings.',
      },
      automations: [
        'Online appointment booking 24/7',
        'Automatic WhatsApp confirmations',
        'Reminders 48h and 2h in advance',
        'Rebooking without phone calls',
        'Regular client reactivation',
        'Review requests after appointments',
        'Product & promotion broadcasts',
        'Client database automatically maintained',
      ],
      faq: [
        { q: 'Does it work with my existing booking software?', a: 'Yes, we integrate Ovivo with most common booking systems. If not, we build a custom system.' },
        { q: 'What if clients prefer to call?', a: 'No problem — the system works in parallel. Those who call are automatically directed to WhatsApp or online booking.' },
        { q: 'How personal are the automatic messages?', a: 'Very personal. The system knows the name, favorite service and last appointments — and writes accordingly.' },
      ],
    },
    ar: {
      slug: 'beauty',
      emoji: '💇',
      badge: 'الصالونات والتجميل',
      heroTitle: 'تقويم ممتلئ دائماً.',
      heroGradient: 'لا مزيد من الإلغاءات.',
      heroSub: 'تخسر صالونات التجميل إيرادات يومياً من الإلغاءات والحجوزات اليدوية. أوفيفو يؤتمت تقويم مواعيدك بالكامل.',
      painPoints: [
        { icon: '🚫', title: 'الإلغاءات تدمر يومك', desc: 'كل إلغاء يكلفك دخلاً ويحجب مواعيد للعملاء الجادين.' },
        { icon: '📱', title: 'دائماً على الهاتف', desc: 'حجز وتأكيد وإعادة جدولة المواعيد — يأكل وقتك الثمين.' },
        { icon: '😴', title: 'لا حجوزات بعد الدوام', desc: 'العملاء يريدون الحجز ليلاً، لكن لا أحد متاح. فرص ضائعة.' },
        { icon: '🔄', title: 'العملاء لا يعودون', desc: 'بدون تذكيرات تلقائية، ينسى العملاء موعدهم القادم.' },
      ],
      solutions: [
        { title: 'حجز أونلاين على مدار الساعة', desc: 'العملاء يحجزون مباشرة عبر واتساب أو موقعك — بدون هاتف ولا انتظار.', result: '+35% حجوزات أكثر' },
        { title: 'تذكيرات تلقائية', desc: 'قبل يومين وساعتين يذكّر النظام العميل تلقائياً — نسبة الإلغاء تنخفض بشكل كبير.', result: '-70% إلغاءات' },
        { title: 'استعادة العملاء الدائمين', desc: 'النظام يكتشف متى لم يزر العميل منذ فترة ويرسل دعوة شخصية تلقائياً.', result: '+25% عملاء متكررون' },
      ],
      stats: [
        { value: '+35%', label: 'حجوزات أكثر' },
        { value: '-70%', label: 'إلغاءات أقل' },
        { value: '2h', label: 'توفير يومي' },
        { value: '+25%', label: 'عملاء دائمون أكثر' },
      ],
      caseStudy: {
        name: 'صالون إليز، برلين',
        result: '-45% إلغاءات، +30% إيرادات',
        quote: 'كنت أتلقى 2-3 إلغاءات يومياً. منذ أوفيفو، تقريباً صفر. التقويم ممتلئ دائماً وأوفر ساعتين يومياً.',
      },
      automations: [
        'حجز مواعيد أونلاين 24/7',
        'تأكيدات واتساب تلقائية',
        'تذكيرات قبل 48 ساعة و2 ساعة',
        'إعادة الجدولة بدون هاتف',
        'إعادة تفعيل العملاء الدائمين',
        'طلب تقييمات بعد الموعد',
        'بث المنتجات والعروض',
        'قاعدة بيانات العملاء محدثة تلقائياً',
      ],
      faq: [
        { q: 'هل يعمل مع برنامج الحجز الموجود؟', a: 'نعم، ندمج أوفيفو مع معظم أنظمة الحجز الشائعة. إذا لم يكن ممكناً، نبني نظاماً مخصصاً.' },
        { q: 'ماذا لو فضّل العملاء الاتصال؟', a: 'لا مشكلة — النظام يعمل بالتوازي. من يتصل يُوجَّه تلقائياً للواتساب أو الحجز الأونلاين.' },
        { q: 'هل الرسائل التلقائية شخصية؟', a: 'جداً. النظام يعرف الاسم والخدمة المفضلة وآخر مواعيد — ويكتب وفقاً لذلك.' },
      ],
    },
  },
  fitness: {
    de: {
      slug: 'fitness',
      emoji: '🏋️',
      badge: 'Fitness & Wellness',
      heroTitle: 'Mehr Mitglieder.',
      heroGradient: 'Weniger Abwanderung.',
      heroSub: 'Fitnessstudios kämpfen täglich mit Mitgliederabwanderung und ineffizienter Kommunikation. Ovivo automatisiert Ihre gesamte Mitgliederkommunikation.',
      painPoints: [
        { icon: '🏃', title: 'Mitglieder kündigen still', desc: 'Mitglieder kommen immer seltener, ohne dass jemand es merkt — bis die Kündigung kommt.' },
        { icon: '📋', title: 'Probe-Trainings gehen verloren', desc: 'Interessenten melden sich an, kommen einmal — und dann hört man nie wieder von ihnen.' },
        { icon: '📱', title: 'Kein Follow-up System', desc: 'Kursplan-Änderungen, Events, Angebote — alles manuell kommuniziert oder vergessen.' },
        { icon: '💸', title: 'Hohe Abwanderungsrate', desc: 'Ohne regelmäßigen Kontakt fühlen sich Mitglieder nicht wertgeschätzt und kündigen.' },
      ],
      solutions: [
        { title: 'Mitglieder-Retention Automation', desc: 'Das System erkennt inaktive Mitglieder und sendet automatisch motivierende Nachrichten und Angebote.', result: '-30% Kündigungen' },
        { title: 'Probe-Training Conversion', desc: 'Jeder Probe-Training-Besucher bekommt eine automatische Follow-up Sequenz — bis zur Mitgliedschaft.', result: '+50% Conversion' },
        { title: 'Kommunikations-Automation', desc: 'Kursplan, Events, Motivations-Nachrichten — alles geht automatisch zur richtigen Zeit raus.', result: '+40% Engagement' },
      ],
      stats: [
        { value: '-30%', label: 'Weniger Kündigungen' },
        { value: '+50%', label: 'Probe → Mitglied' },
        { value: '+40%', label: 'Mehr Engagement' },
        { value: '24/7', label: 'Erreichbar' },
      ],
      caseStudy: {
        name: 'FitLife Studio, Frankfurt',
        result: '-40% Kündigungen in 6 Monaten',
        quote: 'Wir haben die Abwanderungsrate halbiert. Das System erkennt inaktive Mitglieder und spricht sie automatisch an — das hätten wir manuell nie geschafft.',
      },
      automations: [
        'Probe-Training Anmeldung & Follow-up',
        'Mitglieder-Onboarding automatisch',
        'Inaktivitäts-Alerts & Re-Engagement',
        'Kursplan-Updates per WhatsApp',
        'Event & Aktions-Broadcasts',
        'Kündigungs-Prävention Sequenz',
        'Geburtstags- & Jubiläums-Nachrichten',
        'CRM mit kompletter Mitglieder-Historie',
      ],
      faq: [
        { q: 'Funktioniert das auch für kleine Studios?', a: 'Absolut. Gerade kleine Studios profitieren enorm, weil jedes Mitglied zählt.' },
        { q: 'Kann ich die Nachrichten selbst anpassen?', a: 'Ja, Sie geben den Ton vor. Wir helfen bei der Erstellung und passen alles an Ihre Marke an.' },
        { q: 'Wie werden inaktive Mitglieder erkannt?', a: 'Das System trackt Check-ins und Kursbuchungen. Wer länger als X Tage nicht da war, wird automatisch kontaktiert.' },
      ],
    },
    en: {
      slug: 'fitness',
      emoji: '🏋️',
      badge: 'Fitness & Wellness',
      heroTitle: 'More members.',
      heroGradient: 'Less churn.',
      heroSub: 'Fitness studios struggle daily with member churn and inefficient communication. Ovivo automates your entire member communication.',
      painPoints: [
        { icon: '🏃', title: 'Members quit silently', desc: 'Members come less and less without anyone noticing — until the cancellation arrives.' },
        { icon: '📋', title: 'Trial sessions are lost', desc: 'Prospects sign up, come once — and you never hear from them again.' },
        { icon: '📱', title: 'No follow-up system', desc: 'Schedule changes, events, offers — everything communicated manually or forgotten.' },
        { icon: '💸', title: 'High churn rate', desc: 'Without regular contact, members don\'t feel valued and cancel.' },
      ],
      solutions: [
        { title: 'Member retention automation', desc: 'The system identifies inactive members and automatically sends motivating messages and offers.', result: '-30% cancellations' },
        { title: 'Trial session conversion', desc: 'Every trial visitor gets an automatic follow-up sequence — until membership.', result: '+50% conversion' },
        { title: 'Communication automation', desc: 'Schedule, events, motivation messages — everything goes out automatically at the right time.', result: '+40% engagement' },
      ],
      stats: [
        { value: '-30%', label: 'Fewer cancellations' },
        { value: '+50%', label: 'Trial → Member' },
        { value: '+40%', label: 'More engagement' },
        { value: '24/7', label: 'Available' },
      ],
      caseStudy: {
        name: 'FitLife Studio, Frankfurt',
        result: '-40% cancellations in 6 months',
        quote: 'We halved the churn rate. The system detects inactive members and reaches out automatically — we could never have done that manually.',
      },
      automations: [
        'Trial session signup & follow-up',
        'Automatic member onboarding',
        'Inactivity alerts & re-engagement',
        'Schedule updates via WhatsApp',
        'Event & promotion broadcasts',
        'Cancellation prevention sequence',
        'Birthday & milestone messages',
        'CRM with complete member history',
      ],
      faq: [
        { q: 'Does it work for small studios too?', a: 'Absolutely. Small studios benefit enormously because every member counts.' },
        { q: 'Can I customize the messages?', a: 'Yes, you set the tone. We help with creation and adapt everything to your brand.' },
        { q: 'How are inactive members identified?', a: 'The system tracks check-ins and class bookings. Anyone not in for X days is automatically contacted.' },
      ],
    },
    ar: {
      slug: 'fitness',
      emoji: '🏋️',
      badge: 'اللياقة والعافية',
      heroTitle: 'مزيد من الأعضاء.',
      heroGradient: 'أقل إلغاء للاشتراكات.',
      heroSub: 'تعاني صالات اللياقة يومياً من إلغاء الاشتراكات والتواصل غير الفعّال. أوفيفو يؤتمت تواصلك الكامل مع الأعضاء.',
      painPoints: [
        { icon: '🏃', title: 'الأعضاء يغادرون بصمت', desc: 'يأتي الأعضاء بشكل أقل فأقل دون أن يلاحظ أحد — حتى يأتي الإلغاء.' },
        { icon: '📋', title: 'التجارب المجانية تضيع', desc: 'المهتمون يسجلون ويأتون مرة — ثم لا تسمع عنهم مجدداً.' },
        { icon: '📱', title: 'لا نظام متابعة', desc: 'تغيير الجداول والفعاليات والعروض — كل شيء يدوي أو منسي.' },
        { icon: '💸', title: 'معدل إلغاء مرتفع', desc: 'بدون تواصل منتظم، لا يشعر الأعضاء بالتقدير ويلغون.' },
      ],
      solutions: [
        { title: 'أتمتة الاحتفاظ بالأعضاء', desc: 'النظام يكتشف الأعضاء غير النشطين ويرسل رسائل تحفيزية وعروضاً تلقائياً.', result: '-30% إلغاءات' },
        { title: 'تحويل التجارب المجانية', desc: 'كل زائر تجريبي يحصل على سلسلة متابعة تلقائية — حتى الاشتراك.', result: '+50% تحويل' },
        { title: 'أتمتة التواصل', desc: 'الجداول والفعاليات ورسائل التحفيز — كل شيء يصدر تلقائياً في الوقت الصحيح.', result: '+40% تفاعل' },
      ],
      stats: [
        { value: '-30%', label: 'إلغاءات أقل' },
        { value: '+50%', label: 'تجربة → عضوية' },
        { value: '+40%', label: 'تفاعل أكثر' },
        { value: '24/7', label: 'متاح دائماً' },
      ],
      caseStudy: {
        name: 'فيت لايف ستوديو، فرانكفورت',
        result: '-40% إلغاءات في 6 أشهر',
        quote: 'قللنا معدل الإلغاء إلى النصف. النظام يكتشف الأعضاء غير النشطين ويتواصل معهم تلقائياً — لم نكن قادرين على ذلك يدوياً أبداً.',
      },
      automations: [
        'تسجيل التجارب المجانية والمتابعة',
        'استقبال الأعضاء الجدد تلقائياً',
        'تنبيهات عدم النشاط وإعادة التفعيل',
        'تحديثات الجداول عبر واتساب',
        'بث الفعاليات والعروض',
        'سلسلة منع الإلغاء',
        'رسائل أعياد الميلاد والإنجازات',
        'CRM مع سجل كامل للأعضاء',
      ],
      faq: [
        { q: 'هل يعمل للصالات الصغيرة؟', a: 'بالتأكيد. الصالات الصغيرة تستفيد بشكل كبير لأن كل عضو يحسب.' },
        { q: 'هل يمكنني تخصيص الرسائل؟', a: 'نعم، أنت تحدد الأسلوب. نحن نساعد في الإنشاء ونكيّف كل شيء مع علامتك التجارية.' },
        { q: 'كيف يتم اكتشاف الأعضاء غير النشطين؟', a: 'النظام يتتبع تسجيلات الحضور والحجوزات. من لم يأتِ خلال X أيام يُتواصل معه تلقائياً.' },
      ],
    },
  },
};

// Simplified data for hotels and trades
export const hotelsData: Record<string, IndustryData> = {
  de: {
    slug: 'hotels',
    emoji: '🏨',
    badge: 'Hotels & Unterkunft',
    heroTitle: 'Mehr Direktbuchungen.',
    heroGradient: 'Höhere Auslastung.',
    heroSub: 'Hotels verlieren täglich Umsatz an OTAs mit hohen Provisionen. Ovivo hilft Ihnen, Direktbuchungen zu maximieren und Gäste langfristig zu binden.',
    painPoints: [
      { icon: '💸', title: 'OTA-Provisionen fressen Marge', desc: 'Booking.com & Co nehmen 15-25% Provision. Direktbuchungen sind viel profitabler.' },
      { icon: '💬', title: 'Unzählige Anfragen täglich', desc: 'Check-in Zeiten, Parken, Frühstück — dieselben Fragen hundertmal täglich.' },
      { icon: '⭐', title: 'Bewertungsmanagement fehlt', desc: 'Negative Bewertungen bleiben unbeantwortet. Positive werden nicht aktiv gefördert.' },
      { icon: '🔄', title: 'Stammgäste kommen nicht zurück', desc: 'Ohne aktives Follow-up buchen Gäste beim nächsten Mal woanders.' },
    ],
    solutions: [
      { title: 'Direktbuchungs-Funnel', desc: 'Automatische Nachrichten nach OTA-Buchungen animieren Gäste, beim nächsten Mal direkt zu buchen.', result: '+30% Direktbuchungen' },
      { title: 'Gäste-FAQ Automation', desc: 'Check-in, Parken, WLAN, Frühstück — der KI-Assistent beantwortet alles sofort.', result: '-80% manuelle Anfragen' },
      { title: 'Review Management', desc: 'Nach dem Check-out geht automatisch eine Bewertungsanfrage raus. Auf negative Bewertungen wird proaktiv reagiert.', result: '+2 Sterne im Schnitt' },
    ],
    stats: [
      { value: '+30%', label: 'Direktbuchungen' },
      { value: '-80%', label: 'Weniger FAQs' },
      { value: '+2★', label: 'Bessere Bewertungen' },
      { value: '24/7', label: 'Gäste-Support' },
    ],
    caseStudy: {
      name: 'Boutique Hotel am See, Hamburg',
      result: '+28% Direktbuchungen in 4 Monaten',
      quote: 'Die OTA-Abhängigkeit war unser größtes Problem. Mit Ovivo haben wir Direktbuchungen um 28% erhöht und sparen jährlich tausende Euro an Provisionen.',
    },
    automations: [
      'Direktbuchungs-Incentive nach OTA-Buchung',
      'Pre-Arrival Informationen automatisch',
      'Check-in & Check-out Erinnerungen',
      'FAQ-Beantwortung 24/7',
      'Review-Anfragen nach Abreise',
      'Stammgast-Reaktivierung',
      'Sonderangebote & Last-Minute Broadcasts',
      'CRM mit Gäste-Präferenzen',
    ],
    faq: [
      { q: 'Kann das System mit meinem PMS integriert werden?', a: 'Wir integrieren mit den meisten gängigen Property Management Systemen.' },
      { q: 'In welchen Sprachen funktioniert der Assistent?', a: 'Deutsch, Englisch, Arabisch — und weitere Sprachen auf Anfrage.' },
      { q: 'Wie werden Direktbuchungen gefördert?', a: 'Durch automatische Nachrichten mit exklusiven Angeboten für Direktbuchungen beim nächsten Aufenthalt.' },
    ],
  },
  en: {
    slug: 'hotels',
    emoji: '🏨',
    badge: 'Hotels & Accommodation',
    heroTitle: 'More direct bookings.',
    heroGradient: 'Higher occupancy.',
    heroSub: 'Hotels lose daily revenue to OTAs with high commissions. Ovivo helps you maximize direct bookings and retain guests long-term.',
    painPoints: [
      { icon: '💸', title: 'OTA commissions eat margins', desc: 'Booking.com takes 15-25% commission. Direct bookings are much more profitable.' },
      { icon: '💬', title: 'Countless daily inquiries', desc: 'Check-in times, parking, breakfast — the same questions hundreds of times daily.' },
      { icon: '⭐', title: 'No review management', desc: 'Negative reviews go unanswered. Positive ones aren\'t actively promoted.' },
      { icon: '🔄', title: 'Guests don\'t return', desc: 'Without active follow-up, guests book elsewhere next time.' },
    ],
    solutions: [
      { title: 'Direct booking funnel', desc: 'Automatic messages after OTA bookings encourage guests to book directly next time.', result: '+30% direct bookings' },
      { title: 'Guest FAQ automation', desc: 'Check-in, parking, WiFi, breakfast — the AI assistant answers everything instantly.', result: '-80% manual inquiries' },
      { title: 'Review management', desc: 'After checkout, a review request goes out automatically. Negative reviews get proactive responses.', result: '+2 stars on average' },
    ],
    stats: [
      { value: '+30%', label: 'Direct bookings' },
      { value: '-80%', label: 'Fewer FAQs' },
      { value: '+2★', label: 'Better reviews' },
      { value: '24/7', label: 'Guest support' },
    ],
    caseStudy: {
      name: 'Boutique Hotel am See, Hamburg',
      result: '+28% direct bookings in 4 months',
      quote: 'OTA dependency was our biggest problem. With Ovivo we increased direct bookings by 28% and save thousands in commissions annually.',
    },
    automations: [
      'Direct booking incentive after OTA booking',
      'Automatic pre-arrival information',
      'Check-in & check-out reminders',
      'FAQ answering 24/7',
      'Review requests after departure',
      'Returning guest reactivation',
      'Special offers & last-minute broadcasts',
      'CRM with guest preferences',
    ],
    faq: [
      { q: 'Can the system integrate with my PMS?', a: 'We integrate with most common property management systems.' },
      { q: 'What languages does the assistant support?', a: 'German, English, Arabic — and additional languages on request.' },
      { q: 'How are direct bookings promoted?', a: 'Through automatic messages with exclusive offers for direct bookings on the next stay.' },
    ],
  },
  ar: {
    slug: 'hotels',
    emoji: '🏨',
    badge: 'الفنادق والإقامة',
    heroTitle: 'مزيد من الحجوزات المباشرة.',
    heroGradient: 'إشغال أعلى.',
    heroSub: 'تخسر الفنادق إيرادات يومياً لمنصات الحجز ذات العمولات المرتفعة. أوفيفو يساعدك على تعظيم الحجوزات المباشرة والاحتفاظ بالضيوف.',
    painPoints: [
      { icon: '💸', title: 'عمولات المنصات تأكل الأرباح', desc: 'Booking.com تأخذ 15-25% عمولة. الحجوزات المباشرة أكثر ربحية بكثير.' },
      { icon: '💬', title: 'استفسارات لا تنتهي', desc: 'أوقات تسجيل الدخول، الموقف، الإفطار — نفس الأسئلة مئات المرات يومياً.' },
      { icon: '⭐', title: 'لا إدارة للتقييمات', desc: 'التقييمات السلبية تبقى بدون رد. الإيجابية لا تُشجَّع بفعالية.' },
      { icon: '🔄', title: 'الضيوف لا يعودون', desc: 'بدون متابعة فعّالة، يحجز الضيوف في مكان آخر في المرة القادمة.' },
    ],
    solutions: [
      { title: 'قناة حجوزات مباشرة', desc: 'رسائل تلقائية بعد حجوزات المنصات تشجع الضيوف على الحجز مباشرة في المرة القادمة.', result: '+30% حجوزات مباشرة' },
      { title: 'أتمتة الأسئلة الشائعة', desc: 'تسجيل الدخول، الموقف، الواي فاي، الإفطار — المساعد الذكي يجيب على كل شيء فوراً.', result: '-80% استفسارات يدوية' },
      { title: 'إدارة التقييمات', desc: 'بعد المغادرة يصدر طلب تقييم تلقائياً. التقييمات السلبية تحظى برد استباقي.', result: '+2 نجوم في المتوسط' },
    ],
    stats: [
      { value: '+30%', label: 'حجوزات مباشرة' },
      { value: '-80%', label: 'استفسارات أقل' },
      { value: '+2★', label: 'تقييمات أفضل' },
      { value: '24/7', label: 'دعم الضيوف' },
    ],
    caseStudy: {
      name: 'بوتيك هوتل أم زيه، هامبورغ',
      result: '+28% حجوزات مباشرة في 4 أشهر',
      quote: 'الاعتماد على منصات الحجز كان أكبر مشكلتنا. مع أوفيفو رفعنا الحجوزات المباشرة 28% ونوفر آلاف اليوروهات سنوياً من العمولات.',
    },
    automations: [
      'حوافز الحجز المباشر بعد حجوزات المنصات',
      'معلومات ما قبل الوصول تلقائياً',
      'تذكيرات تسجيل الدخول والخروج',
      'الإجابة على الأسئلة الشائعة 24/7',
      'طلب التقييمات بعد المغادرة',
      'إعادة تفعيل الضيوف المتكررين',
      'عروض خاصة وبث اللحظة الأخيرة',
      'CRM مع تفضيلات الضيوف',
    ],
    faq: [
      { q: 'هل يتكامل مع نظام إدارة الممتلكات؟', a: 'ندمج مع معظم أنظمة إدارة الممتلكات الشائعة.' },
      { q: 'ما اللغات التي يدعمها المساعد؟', a: 'الألمانية والإنجليزية والعربية — ولغات إضافية عند الطلب.' },
      { q: 'كيف تُشجَّع الحجوزات المباشرة؟', a: 'من خلال رسائل تلقائية مع عروض حصرية للحجز المباشر في الإقامة القادمة.' },
    ],
  },
};
